// Mocks generated by Mockito 5.0.14 from annotations
// in shop_order_app/test/application/shop_order/shop_order_bloc_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:shop_order_app/domain/entities.dart' as _i3;
import 'package:shop_order_app/domain/i_shop_order_repo.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IShopOrderRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShopOrderRepo extends _i1.Mock implements _i2.IShopOrderRepo {
  MockIShopOrderRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void createNewShopOrder() =>
      super.noSuchMethod(Invocation.method(#createNewShopOrder, []),
          returnValueForMissingStub: null);
  @override
  void createNewUser() =>
      super.noSuchMethod(Invocation.method(#createNewUser, []),
          returnValueForMissingStub: null);
  @override
  List<_i3.ShopOrder> getAllShopOrders() =>
      (super.noSuchMethod(Invocation.method(#getAllShopOrders, []),
          returnValue: <_i3.ShopOrder>[]) as List<_i3.ShopOrder>);
  @override
  void deleteShopOrder(int? id) =>
      super.noSuchMethod(Invocation.method(#deleteShopOrder, [id]),
          returnValueForMissingStub: null);
  @override
  List<_i3.ShopOrder> sortShopOrder(int? columnIndex, bool? isAscending) =>
      (super.noSuchMethod(
          Invocation.method(#sortShopOrder, [columnIndex, isAscending]),
          returnValue: <_i3.ShopOrder>[]) as List<_i3.ShopOrder>);
  @override
  String toString() => super.toString();
}
